/*
 * AUTO-GENERATED by scripts/generate-country-locator-maps.mjs
 *
 * Source: Natural Earth v5.1.1
 * License: Public domain
 *
 * Do not edit by hand.
 */
export interface CountryLocatorAsset {
  code: string;
  name: string;
  file: string;
  markerXPercent: number;
  markerYPercent: number;
}

export const COUNTRY_LOCATOR_WORLD_BASE =
  "assets/Maps/Locator/world-base.svg";

export const COUNTRY_LOCATOR_ASSETS = {
  "AD": {
    "code": "AD",
    "name": "Andorra",
    "file": "assets/Maps/Locator/Countries/ad.svg",
    "markerXPercent": 50.428,
    "markerYPercent": 26.362
  },
  "AE": {
    "code": "AE",
    "name": "United Arab Emirates",
    "file": "assets/Maps/Locator/Countries/ae.svg",
    "markerXPercent": 65.152,
    "markerYPercent": 36.963
  },
  "AF": {
    "code": "AF",
    "name": "Afghanistan",
    "file": "assets/Maps/Locator/Countries/af.svg",
    "markerXPercent": 68.471,
    "markerYPercent": 31.02
  },
  "AG": {
    "code": "AG",
    "name": "Antigua and Barbuda",
    "file": "assets/Maps/Locator/Countries/ag.svg",
    "markerXPercent": 32.836,
    "markerYPercent": 40.36
  },
  "AI": {
    "code": "AI",
    "name": "Anguilla",
    "file": "assets/Maps/Locator/Countries/ai.svg",
    "markerXPercent": 32.493,
    "markerYPercent": 39.865
  },
  "AK": {
    "code": "AK",
    "name": "Akrotiri Sovereign Base Area",
    "file": "assets/Maps/Locator/Countries/ak.svg",
    "markerXPercent": 59.161,
    "markerYPercent": 30.777
  },
  "AL": {
    "code": "AL",
    "name": "Albania",
    "file": "assets/Maps/Locator/Countries/al.svg",
    "markerXPercent": 55.587,
    "markerYPercent": 27.414
  },
  "AM": {
    "code": "AM",
    "name": "Armenia",
    "file": "assets/Maps/Locator/Countries/am.svg",
    "markerXPercent": 62.445,
    "markerYPercent": 27.523
  },
  "AO": {
    "code": "AO",
    "name": "Angola",
    "file": "assets/Maps/Locator/Countries/ao.svg",
    "markerXPercent": 54.996,
    "markerYPercent": 56.768
  },
  "AQ": {
    "code": "AQ",
    "name": "Antarctica",
    "file": "assets/Maps/Locator/Countries/aq.svg",
    "markerXPercent": 59.968,
    "markerYPercent": 94.357
  },
  "AR": {
    "code": "AR",
    "name": "Argentina",
    "file": "assets/Maps/Locator/Countries/ar.svg",
    "markerXPercent": 32.174,
    "markerYPercent": 68.612
  },
  "AS": {
    "code": "AS",
    "name": "American Samoa",
    "file": "assets/Maps/Locator/Countries/as.svg",
    "markerXPercent": 2.57,
    "markerYPercent": 57.959
  },
  "AT": {
    "code": "AT",
    "name": "Austria",
    "file": "assets/Maps/Locator/Countries/at.svg",
    "markerXPercent": 53.925,
    "markerYPercent": 23.601
  },
  "AU": {
    "code": "AU",
    "name": "Australia",
    "file": "assets/Maps/Locator/Countries/au.svg",
    "markerXPercent": 87.236,
    "markerYPercent": 63.405
  },
  "AW": {
    "code": "AW",
    "name": "Aruba",
    "file": "assets/Maps/Locator/Countries/aw.svg",
    "markerXPercent": 30.563,
    "markerYPercent": 43.046
  },
  "AX": {
    "code": "AX",
    "name": "Åland",
    "file": "assets/Maps/Locator/Countries/ax.svg",
    "markerXPercent": 55.519,
    "markerYPercent": 16.58
  },
  "AZ": {
    "code": "AZ",
    "name": "Azerbaijan",
    "file": "assets/Maps/Locator/Countries/az.svg",
    "markerXPercent": 63.114,
    "markerYPercent": 27.554
  },
  "BA": {
    "code": "BA",
    "name": "Bosnia and Herzegovina",
    "file": "assets/Maps/Locator/Countries/ba.svg",
    "markerXPercent": 55.019,
    "markerYPercent": 25.505
  },
  "BB": {
    "code": "BB",
    "name": "Barbados",
    "file": "assets/Maps/Locator/Countries/bb.svg",
    "markerXPercent": 33.453,
    "markerYPercent": 42.687
  },
  "BD": {
    "code": "BD",
    "name": "Bangladesh",
    "file": "assets/Maps/Locator/Countries/bd.svg",
    "markerXPercent": 74.912,
    "markerYPercent": 36.547
  },
  "BE": {
    "code": "BE",
    "name": "Belgium",
    "file": "assets/Maps/Locator/Countries/be.svg",
    "markerXPercent": 51.333,
    "markerYPercent": 21.786
  },
  "BF": {
    "code": "BF",
    "name": "Burkina Faso",
    "file": "assets/Maps/Locator/Countries/bf.svg",
    "markerXPercent": 49.621,
    "markerYPercent": 42.959
  },
  "BG": {
    "code": "BG",
    "name": "Bulgaria",
    "file": "assets/Maps/Locator/Countries/bg.svg",
    "markerXPercent": 56.988,
    "markerYPercent": 26.384
  },
  "BH": {
    "code": "BH",
    "name": "Bahrain",
    "file": "assets/Maps/Locator/Countries/bh.svg",
    "markerXPercent": 64.043,
    "markerYPercent": 35.524
  },
  "BI": {
    "code": "BI",
    "name": "Burundi",
    "file": "assets/Maps/Locator/Countries/bi.svg",
    "markerXPercent": 58.31,
    "markerYPercent": 51.852
  },
  "BJ": {
    "code": "BJ",
    "name": "Benin",
    "file": "assets/Maps/Locator/Countries/bj.svg",
    "markerXPercent": 50.653,
    "markerYPercent": 44.264
  },
  "BL": {
    "code": "BL",
    "name": "Saint Barthélemy",
    "file": "assets/Maps/Locator/Countries/bl.svg",
    "markerXPercent": 32.546,
    "markerYPercent": 40.054
  },
  "BM": {
    "code": "BM",
    "name": "Bermuda",
    "file": "assets/Maps/Locator/Countries/bm.svg",
    "markerXPercent": 32.01,
    "markerYPercent": 32.057
  },
  "BN": {
    "code": "BN",
    "name": "Brunei",
    "file": "assets/Maps/Locator/Countries/bn.svg",
    "markerXPercent": 81.82,
    "markerYPercent": 47.529
  },
  "BO": {
    "code": "BO",
    "name": "Bolivia",
    "file": "assets/Maps/Locator/Countries/bo.svg",
    "markerXPercent": 32.057,
    "markerYPercent": 59.259
  },
  "BR": {
    "code": "BR",
    "name": "Brazil",
    "file": "assets/Maps/Locator/Countries/br.svg",
    "markerXPercent": 36.233,
    "markerYPercent": 56.721
  },
  "BS": {
    "code": "BS",
    "name": "The Bahamas",
    "file": "assets/Maps/Locator/Countries/bs.svg",
    "markerXPercent": 28.57,
    "markerYPercent": 35.332
  },
  "BT": {
    "code": "BT",
    "name": "Bhutan",
    "file": "assets/Maps/Locator/Countries/bt.svg",
    "markerXPercent": 75.011,
    "markerYPercent": 34.702
  },
  "BW": {
    "code": "BW",
    "name": "Botswana",
    "file": "assets/Maps/Locator/Countries/bw.svg",
    "markerXPercent": 56.716,
    "markerYPercent": 62.279
  },
  "BY": {
    "code": "BY",
    "name": "Belarus",
    "file": "assets/Maps/Locator/Countries/by.svg",
    "markerXPercent": 57.894,
    "markerYPercent": 20.099
  },
  "BZ": {
    "code": "BZ",
    "name": "Belize",
    "file": "assets/Maps/Locator/Countries/bz.svg",
    "markerXPercent": 25.358,
    "markerYPercent": 40.443
  },
  "CA": {
    "code": "CA",
    "name": "Canada",
    "file": "assets/Maps/Locator/Countries/ca.svg",
    "markerXPercent": 21.691,
    "markerYPercent": 16.487
  },
  "CD": {
    "code": "CD",
    "name": "Democratic Republic of the Congo",
    "file": "assets/Maps/Locator/Countries/cd.svg",
    "markerXPercent": 56.516,
    "markerYPercent": 51.032
  },
  "CF": {
    "code": "CF",
    "name": "Central African Republic",
    "file": "assets/Maps/Locator/Countries/cf.svg",
    "markerXPercent": 55.807,
    "markerYPercent": 46.117
  },
  "CG": {
    "code": "CG",
    "name": "Republic of the Congo",
    "file": "assets/Maps/Locator/Countries/cg.svg",
    "markerXPercent": 54.417,
    "markerYPercent": 49.921
  },
  "CH": {
    "code": "CH",
    "name": "Switzerland",
    "file": "assets/Maps/Locator/Countries/ch.svg",
    "markerXPercent": 52.073,
    "markerYPercent": 24.045
  },
  "CI": {
    "code": "CI",
    "name": "Ivory Coast",
    "file": "assets/Maps/Locator/Countries/ci.svg",
    "markerXPercent": 48.453,
    "markerYPercent": 45.838
  },
  "CK": {
    "code": "CK",
    "name": "Cook Islands",
    "file": "assets/Maps/Locator/Countries/ck.svg",
    "markerXPercent": 5.615,
    "markerYPercent": 61.787
  },
  "CL": {
    "code": "CL",
    "name": "Chile",
    "file": "assets/Maps/Locator/Countries/cl.svg",
    "markerXPercent": 29.911,
    "markerYPercent": 71.195
  },
  "CM": {
    "code": "CM",
    "name": "Cameroon",
    "file": "assets/Maps/Locator/Countries/cm.svg",
    "markerXPercent": 53.465,
    "markerYPercent": 47.453
  },
  "CN": {
    "code": "CN",
    "name": "People's Republic of China",
    "file": "assets/Maps/Locator/Countries/cn.svg",
    "markerXPercent": 79.538,
    "markerYPercent": 31.945
  },
  "CO": {
    "code": "CO",
    "name": "Colombia",
    "file": "assets/Maps/Locator/Countries/co.svg",
    "markerXPercent": 29.674,
    "markerYPercent": 48.126
  },
  "CR": {
    "code": "CR",
    "name": "Costa Rica",
    "file": "assets/Maps/Locator/Countries/cr.svg",
    "markerXPercent": 26.645,
    "markerYPercent": 44.408
  },
  "CU": {
    "code": "CU",
    "name": "Cuba",
    "file": "assets/Maps/Locator/Countries/cu.svg",
    "markerXPercent": 28.34,
    "markerYPercent": 38.148
  },
  "CV": {
    "code": "CV",
    "name": "Cape Verde",
    "file": "assets/Maps/Locator/Countries/cv.svg",
    "markerXPercent": 43.433,
    "markerYPercent": 41.625
  },
  "CW": {
    "code": "CW",
    "name": "Curaçao",
    "file": "assets/Maps/Locator/Countries/cw.svg",
    "markerXPercent": 30.855,
    "markerYPercent": 43.253
  },
  "CY": {
    "code": "CY",
    "name": "Cyprus",
    "file": "assets/Maps/Locator/Countries/cy.svg",
    "markerXPercent": 59.19,
    "markerYPercent": 30.604
  },
  "CZ": {
    "code": "CZ",
    "name": "Czech Republic",
    "file": "assets/Maps/Locator/Countries/cz.svg",
    "markerXPercent": 54.272,
    "markerYPercent": 22.288
  },
  "DE": {
    "code": "DE",
    "name": "Germany",
    "file": "assets/Maps/Locator/Countries/de.svg",
    "markerXPercent": 52.688,
    "markerYPercent": 21.688
  },
  "DH": {
    "code": "DH",
    "name": "Dhekelia Cantonment",
    "file": "assets/Maps/Locator/Countries/dh.svg",
    "markerXPercent": 59.386,
    "markerYPercent": 30.549
  },
  "DJ": {
    "code": "DJ",
    "name": "Djibouti",
    "file": "assets/Maps/Locator/Countries/dj.svg",
    "markerXPercent": 61.805,
    "markerYPercent": 43.346
  },
  "DK": {
    "code": "DK",
    "name": "Denmark",
    "file": "assets/Maps/Locator/Countries/dk.svg",
    "markerXPercent": 52.505,
    "markerYPercent": 18.907
  },
  "DM": {
    "code": "DM",
    "name": "Dominica",
    "file": "assets/Maps/Locator/Countries/dm.svg",
    "markerXPercent": 32.96,
    "markerYPercent": 41.412
  },
  "DO": {
    "code": "DO",
    "name": "Dominican Republic",
    "file": "assets/Maps/Locator/Countries/do.svg",
    "markerXPercent": 30.374,
    "markerYPercent": 39.387
  },
  "DZ": {
    "code": "DZ",
    "name": "Algeria",
    "file": "assets/Maps/Locator/Countries/dz.svg",
    "markerXPercent": 50.78,
    "markerYPercent": 34.779
  },
  "EC": {
    "code": "EC",
    "name": "Ecuador",
    "file": "assets/Maps/Locator/Countries/ec.svg",
    "markerXPercent": 28.281,
    "markerYPercent": 50.699
  },
  "EE": {
    "code": "EE",
    "name": "Estonia",
    "file": "assets/Maps/Locator/Countries/ee.svg",
    "markerXPercent": 57.185,
    "markerYPercent": 17.375
  },
  "EG": {
    "code": "EG",
    "name": "Egypt",
    "file": "assets/Maps/Locator/Countries/eg.svg",
    "markerXPercent": 58.179,
    "markerYPercent": 35.452
  },
  "EH": {
    "code": "EH",
    "name": "Western Sahara",
    "file": "assets/Maps/Locator/Countries/eh.svg",
    "markerXPercent": 46.492,
    "markerYPercent": 36.685
  },
  "ER": {
    "code": "ER",
    "name": "Eritrea",
    "file": "assets/Maps/Locator/Countries/er.svg",
    "markerXPercent": 60.635,
    "markerYPercent": 41.229
  },
  "ES": {
    "code": "ES",
    "name": "Spain",
    "file": "assets/Maps/Locator/Countries/es.svg",
    "markerXPercent": 49.038,
    "markerYPercent": 27.727
  },
  "ET": {
    "code": "ET",
    "name": "Ethiopia",
    "file": "assets/Maps/Locator/Countries/et.svg",
    "markerXPercent": 60.858,
    "markerYPercent": 45.537
  },
  "FI": {
    "code": "FI",
    "name": "Finland",
    "file": "assets/Maps/Locator/Countries/fi.svg",
    "markerXPercent": 57.577,
    "markerYPercent": 14.86
  },
  "FJ": {
    "code": "FJ",
    "name": "Fiji",
    "file": "assets/Maps/Locator/Countries/fj.svg",
    "markerXPercent": 99.438,
    "markerYPercent": 59.903
  },
  "FK": {
    "code": "FK",
    "name": "Falkland Islands",
    "file": "assets/Maps/Locator/Countries/fk.svg",
    "markerXPercent": 33.684,
    "markerYPercent": 78.672
  },
  "FM": {
    "code": "FM",
    "name": "Federated States of Micronesia",
    "file": "assets/Maps/Locator/Countries/fm.svg",
    "markerXPercent": 93.954,
    "markerYPercent": 46.174
  },
  "FO": {
    "code": "FO",
    "name": "Faroe Islands",
    "file": "assets/Maps/Locator/Countries/fo.svg",
    "markerXPercent": 48.039,
    "markerYPercent": 15.452
  },
  "FR": {
    "code": "FR",
    "name": "France",
    "file": "assets/Maps/Locator/Countries/fr.svg",
    "markerXPercent": 50.709,
    "markerYPercent": 24.058
  },
  "GA": {
    "code": "GA",
    "name": "Gabon",
    "file": "assets/Maps/Locator/Countries/ga.svg",
    "markerXPercent": 53.288,
    "markerYPercent": 50.243
  },
  "GB": {
    "code": "GB",
    "name": "United Kingdom",
    "file": "assets/Maps/Locator/Countries/gb.svg",
    "markerXPercent": 49.412,
    "markerYPercent": 19.776
  },
  "GD": {
    "code": "GD",
    "name": "Grenada",
    "file": "assets/Maps/Locator/Countries/gd.svg",
    "markerXPercent": 32.867,
    "markerYPercent": 43.27
  },
  "GE": {
    "code": "GE",
    "name": "Georgia",
    "file": "assets/Maps/Locator/Countries/ge.svg",
    "markerXPercent": 62.149,
    "markerYPercent": 26.739
  },
  "GG": {
    "code": "GG",
    "name": "Guernsey",
    "file": "assets/Maps/Locator/Countries/gg.svg",
    "markerXPercent": 49.288,
    "markerYPercent": 22.52
  },
  "GH": {
    "code": "GH",
    "name": "Ghana",
    "file": "assets/Maps/Locator/Countries/gh.svg",
    "markerXPercent": 49.712,
    "markerYPercent": 45.712
  },
  "GI": {
    "code": "GI",
    "name": "Gibraltar",
    "file": "assets/Maps/Locator/Countries/gi.svg",
    "markerXPercent": 48.515,
    "markerYPercent": 29.928
  },
  "GL": {
    "code": "GL",
    "name": "Greenland",
    "file": "assets/Maps/Locator/Countries/gl.svg",
    "markerXPercent": 39.074,
    "markerYPercent": 8.711
  },
  "GM": {
    "code": "GM",
    "name": "The Gambia",
    "file": "assets/Maps/Locator/Countries/gm.svg",
    "markerXPercent": 45.834,
    "markerYPercent": 42.421
  },
  "GN": {
    "code": "GN",
    "name": "Guinea",
    "file": "assets/Maps/Locator/Countries/gn.svg",
    "markerXPercent": 47.218,
    "markerYPercent": 44.101
  },
  "GQ": {
    "code": "GQ",
    "name": "Equatorial Guinea",
    "file": "assets/Maps/Locator/Countries/gq.svg",
    "markerXPercent": 52.497,
    "markerYPercent": 48.704
  },
  "GR": {
    "code": "GR",
    "name": "Greece",
    "file": "assets/Maps/Locator/Countries/gr.svg",
    "markerXPercent": 56.035,
    "markerYPercent": 28.06
  },
  "GS": {
    "code": "GS",
    "name": "South Georgia and the South Sandwich Islands",
    "file": "assets/Maps/Locator/Countries/gs.svg",
    "markerXPercent": 41.371,
    "markerYPercent": 80.935
  },
  "GT": {
    "code": "GT",
    "name": "Guatemala",
    "file": "assets/Maps/Locator/Countries/gt.svg",
    "markerXPercent": 24.862,
    "markerYPercent": 41.677
  },
  "GU": {
    "code": "GU",
    "name": "Guam",
    "file": "assets/Maps/Locator/Countries/gu.svg",
    "markerXPercent": 90.195,
    "markerYPercent": 42.581
  },
  "GW": {
    "code": "GW",
    "name": "Guinea-Bissau",
    "file": "assets/Maps/Locator/Countries/gw.svg",
    "markerXPercent": 45.966,
    "markerYPercent": 43.242
  },
  "GY": {
    "code": "GY",
    "name": "Guyana",
    "file": "assets/Maps/Locator/Countries/gy.svg",
    "markerXPercent": 33.627,
    "markerYPercent": 47.153
  },
  "HK": {
    "code": "HK",
    "name": "Hong Kong",
    "file": "assets/Maps/Locator/Countries/hk.svg",
    "markerXPercent": 81.694,
    "markerYPercent": 37.528
  },
  "HM": {
    "code": "HM",
    "name": "Heard Island and McDonald Islands",
    "file": "assets/Maps/Locator/Countries/hm.svg",
    "markerXPercent": 70.418,
    "markerYPercent": 79.502
  },
  "HN": {
    "code": "HN",
    "name": "Honduras",
    "file": "assets/Maps/Locator/Countries/hn.svg",
    "markerXPercent": 25.865,
    "markerYPercent": 41.781
  },
  "HR": {
    "code": "HR",
    "name": "Croatia",
    "file": "assets/Maps/Locator/Countries/hr.svg",
    "markerXPercent": 54.548,
    "markerYPercent": 24.552
  },
  "HT": {
    "code": "HT",
    "name": "Haiti",
    "file": "assets/Maps/Locator/Countries/ht.svg",
    "markerXPercent": 29.938,
    "markerYPercent": 39.298
  },
  "HU": {
    "code": "HU",
    "name": "Hungary",
    "file": "assets/Maps/Locator/Countries/hu.svg",
    "markerXPercent": 55.402,
    "markerYPercent": 23.841
  },
  "ID": {
    "code": "ID",
    "name": "Indonesia",
    "file": "assets/Maps/Locator/Countries/id.svg",
    "markerXPercent": 78.304,
    "markerYPercent": 50.53
  },
  "IE": {
    "code": "IE",
    "name": "Ireland",
    "file": "assets/Maps/Locator/Countries/ie.svg",
    "markerXPercent": 47.834,
    "markerYPercent": 20.512
  },
  "IL": {
    "code": "IL",
    "name": "Israel",
    "file": "assets/Maps/Locator/Countries/il.svg",
    "markerXPercent": 59.68,
    "markerYPercent": 32.827
  },
  "IM": {
    "code": "IM",
    "name": "Isle of Man",
    "file": "assets/Maps/Locator/Countries/im.svg",
    "markerXPercent": 48.742,
    "markerYPercent": 19.877
  },
  "IN": {
    "code": "IN",
    "name": "India",
    "file": "assets/Maps/Locator/Countries/in.svg",
    "markerXPercent": 72.044,
    "markerYPercent": 37.396
  },
  "IO": {
    "code": "IO",
    "name": "British Indian Ocean Territory",
    "file": "assets/Maps/Locator/Countries/io.svg",
    "markerXPercent": 69.819,
    "markerYPercent": 53.439
  },
  "IQ": {
    "code": "IQ",
    "name": "Iraq",
    "file": "assets/Maps/Locator/Countries/iq.svg",
    "markerXPercent": 62.017,
    "markerYPercent": 31.614
  },
  "IR": {
    "code": "IR",
    "name": "Iran",
    "file": "assets/Maps/Locator/Countries/ir.svg",
    "markerXPercent": 65.259,
    "markerYPercent": 32.13
  },
  "IS": {
    "code": "IS",
    "name": "Iceland",
    "file": "assets/Maps/Locator/Countries/is.svg",
    "markerXPercent": 44.813,
    "markerYPercent": 14.012
  },
  "IT": {
    "code": "IT",
    "name": "Italy",
    "file": "assets/Maps/Locator/Countries/it.svg",
    "markerXPercent": 53.077,
    "markerYPercent": 25.149
  },
  "JE": {
    "code": "JE",
    "name": "Jersey",
    "file": "assets/Maps/Locator/Countries/je.svg",
    "markerXPercent": 49.419,
    "markerYPercent": 22.655
  },
  "JM": {
    "code": "JM",
    "name": "Jamaica",
    "file": "assets/Maps/Locator/Countries/jm.svg",
    "markerXPercent": 28.523,
    "markerYPercent": 39.924
  },
  "JO": {
    "code": "JO",
    "name": "Jordan",
    "file": "assets/Maps/Locator/Countries/jo.svg",
    "markerXPercent": 60.104,
    "markerYPercent": 32.886
  },
  "JP": {
    "code": "JP",
    "name": "Japan",
    "file": "assets/Maps/Locator/Countries/jp.svg",
    "markerXPercent": 88.456,
    "markerYPercent": 29.921
  },
  "KE": {
    "code": "KE",
    "name": "Kenya",
    "file": "assets/Maps/Locator/Countries/ke.svg",
    "markerXPercent": 60.53,
    "markerYPercent": 49.695
  },
  "KG": {
    "code": "KG",
    "name": "Kyrgyzstan",
    "file": "assets/Maps/Locator/Countries/kg.svg",
    "markerXPercent": 70.704,
    "markerYPercent": 26.851
  },
  "KH": {
    "code": "KH",
    "name": "Cambodia",
    "file": "assets/Maps/Locator/Countries/kh.svg",
    "markerXPercent": 79.029,
    "markerYPercent": 42.974
  },
  "KI": {
    "code": "KI",
    "name": "Kiribati",
    "file": "assets/Maps/Locator/Countries/ki.svg",
    "markerXPercent": 6.282,
    "markerYPercent": 48.989
  },
  "KM": {
    "code": "KM",
    "name": "Comoros",
    "file": "assets/Maps/Locator/Countries/km.svg",
    "markerXPercent": 62.033,
    "markerYPercent": 56.515
  },
  "KN": {
    "code": "KN",
    "name": "Saint Kitts and Nevis",
    "file": "assets/Maps/Locator/Countries/kn.svg",
    "markerXPercent": 32.567,
    "markerYPercent": 40.369
  },
  "KP": {
    "code": "KP",
    "name": "North Korea",
    "file": "assets/Maps/Locator/Countries/kp.svg",
    "markerXPercent": 85.123,
    "markerYPercent": 27.842
  },
  "KR": {
    "code": "KR",
    "name": "South Korea",
    "file": "assets/Maps/Locator/Countries/kr.svg",
    "markerXPercent": 85.592,
    "markerYPercent": 29.786
  },
  "KW": {
    "code": "KW",
    "name": "Kuwait",
    "file": "assets/Maps/Locator/Countries/kw.svg",
    "markerXPercent": 63.143,
    "markerYPercent": 33.659
  },
  "KY": {
    "code": "KY",
    "name": "Cayman Islands",
    "file": "assets/Maps/Locator/Countries/ky.svg",
    "markerXPercent": 27.433,
    "markerYPercent": 39.267
  },
  "KZ": {
    "code": "KZ",
    "name": "Kazakhstan",
    "file": "assets/Maps/Locator/Countries/kz.svg",
    "markerXPercent": 69.079,
    "markerYPercent": 22.748
  },
  "LA": {
    "code": "LA",
    "name": "Laos",
    "file": "assets/Maps/Locator/Countries/la.svg",
    "markerXPercent": 78.482,
    "markerYPercent": 39.205
  },
  "LB": {
    "code": "LB",
    "name": "Lebanon",
    "file": "assets/Maps/Locator/Countries/lb.svg",
    "markerXPercent": 59.998,
    "markerYPercent": 31.037
  },
  "LC": {
    "code": "LC",
    "name": "Saint Lucia",
    "file": "assets/Maps/Locator/Countries/lc.svg",
    "markerXPercent": 33.061,
    "markerYPercent": 42.282
  },
  "LI": {
    "code": "LI",
    "name": "Liechtenstein",
    "file": "assets/Maps/Locator/Countries/li.svg",
    "markerXPercent": 52.655,
    "markerYPercent": 23.827
  },
  "LK": {
    "code": "LK",
    "name": "Sri Lanka",
    "file": "assets/Maps/Locator/Countries/lk.svg",
    "markerXPercent": 72.418,
    "markerYPercent": 45.788
  },
  "LR": {
    "code": "LR",
    "name": "Liberia",
    "file": "assets/Maps/Locator/Countries/lr.svg",
    "markerXPercent": 47.372,
    "markerYPercent": 46.418
  },
  "LS": {
    "code": "LS",
    "name": "Lesotho",
    "file": "assets/Maps/Locator/Countries/ls.svg",
    "markerXPercent": 57.846,
    "markerYPercent": 66.378
  },
  "LT": {
    "code": "LT",
    "name": "Lithuania",
    "file": "assets/Maps/Locator/Countries/lt.svg",
    "markerXPercent": 56.692,
    "markerYPercent": 19.387
  },
  "LU": {
    "code": "LU",
    "name": "Luxembourg",
    "file": "assets/Maps/Locator/Countries/lu.svg",
    "markerXPercent": 51.688,
    "markerYPercent": 22.37
  },
  "LV": {
    "code": "LV",
    "name": "Latvia",
    "file": "assets/Maps/Locator/Countries/lv.svg",
    "markerXPercent": 57.072,
    "markerYPercent": 18.296
  },
  "LY": {
    "code": "LY",
    "name": "Libya",
    "file": "assets/Maps/Locator/Countries/ly.svg",
    "markerXPercent": 55.003,
    "markerYPercent": 35.201
  },
  "MA": {
    "code": "MA",
    "name": "Morocco",
    "file": "assets/Maps/Locator/Countries/ma.svg",
    "markerXPercent": 48.004,
    "markerYPercent": 32.416
  },
  "MC": {
    "code": "MC",
    "name": "Monaco",
    "file": "assets/Maps/Locator/Countries/mc.svg",
    "markerXPercent": 52.055,
    "markerYPercent": 25.7
  },
  "MD": {
    "code": "MD",
    "name": "Moldova",
    "file": "assets/Maps/Locator/Countries/md.svg",
    "markerXPercent": 57.913,
    "markerYPercent": 23.647
  },
  "ME": {
    "code": "ME",
    "name": "Montenegro",
    "file": "assets/Maps/Locator/Countries/me.svg",
    "markerXPercent": 55.318,
    "markerYPercent": 26.22
  },
  "MF": {
    "code": "MF",
    "name": "Saint Martin",
    "file": "assets/Maps/Locator/Countries/mf.svg",
    "markerXPercent": 32.486,
    "markerYPercent": 39.955
  },
  "MG": {
    "code": "MG",
    "name": "Madagascar",
    "file": "assets/Maps/Locator/Countries/mg.svg",
    "markerXPercent": 62.973,
    "markerYPercent": 60.349
  },
  "MH": {
    "code": "MH",
    "name": "Marshall Islands",
    "file": "assets/Maps/Locator/Countries/mh.svg",
    "markerXPercent": 97.554,
    "markerYPercent": 46.065
  },
  "MK": {
    "code": "MK",
    "name": "North Macedonia",
    "file": "assets/Maps/Locator/Countries/mk.svg",
    "markerXPercent": 55.988,
    "markerYPercent": 26.912
  },
  "ML": {
    "code": "ML",
    "name": "Mali",
    "file": "assets/Maps/Locator/Countries/ml.svg",
    "markerXPercent": 49.434,
    "markerYPercent": 39.615
  },
  "MM": {
    "code": "MM",
    "name": "Myanmar",
    "file": "assets/Maps/Locator/Countries/mm.svg",
    "markerXPercent": 76.612,
    "markerYPercent": 38.015
  },
  "MN": {
    "code": "MN",
    "name": "Mongolia",
    "file": "assets/Maps/Locator/Countries/mn.svg",
    "markerXPercent": 78.931,
    "markerYPercent": 24.446
  },
  "MO": {
    "code": "MO",
    "name": "Macau",
    "file": "assets/Maps/Locator/Countries/mo.svg",
    "markerXPercent": 81.543,
    "markerYPercent": 37.706
  },
  "MP": {
    "code": "MP",
    "name": "Northern Mariana Islands",
    "file": "assets/Maps/Locator/Countries/mp.svg",
    "markerXPercent": 90.482,
    "markerYPercent": 41.562
  },
  "MR": {
    "code": "MR",
    "name": "Mauritania",
    "file": "assets/Maps/Locator/Countries/mr.svg",
    "markerXPercent": 47.294,
    "markerYPercent": 39.118
  },
  "MS": {
    "code": "MS",
    "name": "Montserrat",
    "file": "assets/Maps/Locator/Countries/ms.svg",
    "markerXPercent": 32.725,
    "markerYPercent": 40.702
  },
  "MT": {
    "code": "MT",
    "name": "Malta",
    "file": "assets/Maps/Locator/Countries/mt.svg",
    "markerXPercent": 54.009,
    "markerYPercent": 30.06
  },
  "MU": {
    "code": "MU",
    "name": "Mauritius",
    "file": "assets/Maps/Locator/Countries/mu.svg",
    "markerXPercent": 65.991,
    "markerYPercent": 61.278
  },
  "MV": {
    "code": "MV",
    "name": "Maldives",
    "file": "assets/Maps/Locator/Countries/mv.svg",
    "markerXPercent": 70.419,
    "markerYPercent": 47.681
  },
  "MW": {
    "code": "MW",
    "name": "Malawi",
    "file": "assets/Maps/Locator/Countries/mw.svg",
    "markerXPercent": 59.336,
    "markerYPercent": 57.437
  },
  "MX": {
    "code": "MX",
    "name": "Mexico",
    "file": "assets/Maps/Locator/Countries/mx.svg",
    "markerXPercent": 21.586,
    "markerYPercent": 36.711
  },
  "MY": {
    "code": "MY",
    "name": "Malaysia",
    "file": "assets/Maps/Locator/Countries/my.svg",
    "markerXPercent": 81.621,
    "markerYPercent": 48.595
  },
  "MZ": {
    "code": "MZ",
    "name": "Mozambique",
    "file": "assets/Maps/Locator/Countries/mz.svg",
    "markerXPercent": 60.511,
    "markerYPercent": 57.746
  },
  "NA": {
    "code": "NA",
    "name": "Namibia",
    "file": "assets/Maps/Locator/Countries/na.svg",
    "markerXPercent": 54.752,
    "markerYPercent": 61.431
  },
  "NC": {
    "code": "NC",
    "name": "New Caledonia",
    "file": "assets/Maps/Locator/Countries/nc.svg",
    "markerXPercent": 95.857,
    "markerYPercent": 61.703
  },
  "NE": {
    "code": "NE",
    "name": "Niger",
    "file": "assets/Maps/Locator/Countries/ne.svg",
    "markerXPercent": 52.64,
    "markerYPercent": 40.308
  },
  "NF": {
    "code": "NF",
    "name": "Norfolk Island",
    "file": "assets/Maps/Locator/Countries/nf.svg",
    "markerXPercent": 96.654,
    "markerYPercent": 66.129
  },
  "NG": {
    "code": "NG",
    "name": "Nigeria",
    "file": "assets/Maps/Locator/Countries/ng.svg",
    "markerXPercent": 52.084,
    "markerYPercent": 44.756
  },
  "NI": {
    "code": "NI",
    "name": "Nicaragua",
    "file": "assets/Maps/Locator/Countries/ni.svg",
    "markerXPercent": 26.37,
    "markerYPercent": 42.961
  },
  "NL": {
    "code": "NL",
    "name": "Netherlands",
    "file": "assets/Maps/Locator/Countries/nl.svg",
    "markerXPercent": 51.559,
    "markerYPercent": 20.877
  },
  "NO": {
    "code": "NO",
    "name": "Norway",
    "file": "assets/Maps/Locator/Countries/no.svg",
    "markerXPercent": 52.689,
    "markerYPercent": 15.913
  },
  "NP": {
    "code": "NP",
    "name": "Nepal",
    "file": "assets/Maps/Locator/Countries/np.svg",
    "markerXPercent": 73.233,
    "markerYPercent": 34.279
  },
  "NR": {
    "code": "NR",
    "name": "Nauru",
    "file": "assets/Maps/Locator/Countries/nr.svg",
    "markerXPercent": 96.37,
    "markerYPercent": 50.289
  },
  "NU": {
    "code": "NU",
    "name": "Niue",
    "file": "assets/Maps/Locator/Countries/nu.svg",
    "markerXPercent": 2.816,
    "markerYPercent": 60.581
  },
  "NZ": {
    "code": "NZ",
    "name": "New Zealand",
    "file": "assets/Maps/Locator/Countries/nz.svg",
    "markerXPercent": 97.996,
    "markerYPercent": 72.088
  },
  "OM": {
    "code": "OM",
    "name": "Oman",
    "file": "assets/Maps/Locator/Countries/om.svg",
    "markerXPercent": 65.927,
    "markerYPercent": 37.711
  },
  "PA": {
    "code": "PA",
    "name": "Panama",
    "file": "assets/Maps/Locator/Countries/pa.svg",
    "markerXPercent": 27.68,
    "markerYPercent": 45.154
  },
  "PE": {
    "code": "PE",
    "name": "Peru",
    "file": "assets/Maps/Locator/Countries/pe.svg",
    "markerXPercent": 29.75,
    "markerYPercent": 57.209
  },
  "PF": {
    "code": "PF",
    "name": "French Polynesia",
    "file": "assets/Maps/Locator/Countries/pf.svg",
    "markerXPercent": 8.483,
    "markerYPercent": 59.793
  },
  "PG": {
    "code": "PG",
    "name": "Papua New Guinea",
    "file": "assets/Maps/Locator/Countries/pg.svg",
    "markerXPercent": 89.975,
    "markerYPercent": 53.164
  },
  "PH": {
    "code": "PH",
    "name": "Philippines",
    "file": "assets/Maps/Locator/Countries/ph.svg",
    "markerXPercent": 84.018,
    "markerYPercent": 43.779
  },
  "PK": {
    "code": "PK",
    "name": "Pakistan",
    "file": "assets/Maps/Locator/Countries/pk.svg",
    "markerXPercent": 69.04,
    "markerYPercent": 33.706
  },
  "PL": {
    "code": "PL",
    "name": "Poland",
    "file": "assets/Maps/Locator/Countries/pl.svg",
    "markerXPercent": 55.414,
    "markerYPercent": 21.116
  },
  "PM": {
    "code": "PM",
    "name": "Saint Pierre and Miquelon",
    "file": "assets/Maps/Locator/Countries/pm.svg",
    "markerXPercent": 34.352,
    "markerYPercent": 23.866
  },
  "PN": {
    "code": "PN",
    "name": "Pitcairn Islands",
    "file": "assets/Maps/Locator/Countries/pn.svg",
    "markerXPercent": 14.356,
    "markerYPercent": 63.536
  },
  "PR": {
    "code": "PR",
    "name": "Puerto Rico",
    "file": "assets/Maps/Locator/Countries/pr.svg",
    "markerXPercent": 31.533,
    "markerYPercent": 39.87
  },
  "PS": {
    "code": "PS",
    "name": "Palestine",
    "file": "assets/Maps/Locator/Countries/ps.svg",
    "markerXPercent": 59.803,
    "markerYPercent": 32.196
  },
  "PT": {
    "code": "PT",
    "name": "Portugal",
    "file": "assets/Maps/Locator/Countries/pt.svg",
    "markerXPercent": 47.702,
    "markerYPercent": 27.996
  },
  "PW": {
    "code": "PW",
    "name": "Palau",
    "file": "assets/Maps/Locator/Countries/pw.svg",
    "markerXPercent": 87.383,
    "markerYPercent": 45.823
  },
  "PY": {
    "code": "PY",
    "name": "Paraguay",
    "file": "assets/Maps/Locator/Countries/py.svg",
    "markerXPercent": 33.293,
    "markerYPercent": 62.041
  },
  "QA": {
    "code": "QA",
    "name": "Qatar",
    "file": "assets/Maps/Locator/Countries/qa.svg",
    "markerXPercent": 64.207,
    "markerYPercent": 35.979
  },
  "RO": {
    "code": "RO",
    "name": "Romania",
    "file": "assets/Maps/Locator/Countries/ro.svg",
    "markerXPercent": 56.937,
    "markerYPercent": 24.593
  },
  "RS": {
    "code": "RS",
    "name": "Serbia",
    "file": "assets/Maps/Locator/Countries/rs.svg",
    "markerXPercent": 55.774,
    "markerYPercent": 25.45
  },
  "RU": {
    "code": "RU",
    "name": "Russia",
    "file": "assets/Maps/Locator/Countries/ru.svg",
    "markerXPercent": 62.413,
    "markerYPercent": 17.639
  },
  "RW": {
    "code": "RW",
    "name": "Rwanda",
    "file": "assets/Maps/Locator/Countries/rw.svg",
    "markerXPercent": 58.362,
    "markerYPercent": 51.054
  },
  "SA": {
    "code": "SA",
    "name": "Saudi Arabia",
    "file": "assets/Maps/Locator/Countries/sa.svg",
    "markerXPercent": 62.417,
    "markerYPercent": 36.774
  },
  "SB": {
    "code": "SB",
    "name": "Solomon Islands",
    "file": "assets/Maps/Locator/Countries/sb.svg",
    "markerXPercent": 94.214,
    "markerYPercent": 54.461
  },
  "SC": {
    "code": "SC",
    "name": "Seychelles",
    "file": "assets/Maps/Locator/Countries/sc.svg",
    "markerXPercent": 65.411,
    "markerYPercent": 52.598
  },
  "SD": {
    "code": "SD",
    "name": "Sudan",
    "file": "assets/Maps/Locator/Countries/sd.svg",
    "markerXPercent": 58.128,
    "markerYPercent": 40.927
  },
  "SE": {
    "code": "SE",
    "name": "Sweden",
    "file": "assets/Maps/Locator/Countries/se.svg",
    "markerXPercent": 55.283,
    "markerYPercent": 13.412
  },
  "SG": {
    "code": "SG",
    "name": "Siachen Glacier",
    "file": "assets/Maps/Locator/Countries/sg.svg",
    "markerXPercent": 71.425,
    "markerYPercent": 30.366
  },
  "SH": {
    "code": "SH",
    "name": "Saint Helena",
    "file": "assets/Maps/Locator/Countries/sh.svg",
    "markerXPercent": 48.413,
    "markerYPercent": 58.861
  },
  "SI": {
    "code": "SI",
    "name": "Slovenia",
    "file": "assets/Maps/Locator/Countries/si.svg",
    "markerXPercent": 54.143,
    "markerYPercent": 24.411
  },
  "SK": {
    "code": "SK",
    "name": "Slovakia",
    "file": "assets/Maps/Locator/Countries/sk.svg",
    "markerXPercent": 55.292,
    "markerYPercent": 22.926
  },
  "SL": {
    "code": "SL",
    "name": "Somaliland",
    "file": "assets/Maps/Locator/Countries/sl.svg",
    "markerXPercent": 62.981,
    "markerYPercent": 44.753
  },
  "SM": {
    "code": "SM",
    "name": "San Marino",
    "file": "assets/Maps/Locator/Countries/sm.svg",
    "markerXPercent": 53.456,
    "markerYPercent": 25.592
  },
  "SN": {
    "code": "SN",
    "name": "Senegal",
    "file": "assets/Maps/Locator/Countries/sn.svg",
    "markerXPercent": 45.895,
    "markerYPercent": 41.59
  },
  "SO": {
    "code": "SO",
    "name": "Somalia",
    "file": "assets/Maps/Locator/Countries/so.svg",
    "markerXPercent": 62.553,
    "markerYPercent": 48.017
  },
  "SP": {
    "code": "SP",
    "name": "Wake Island",
    "file": "assets/Maps/Locator/Countries/sp.svg",
    "markerXPercent": 82.172,
    "markerYPercent": 44.039
  },
  "SR": {
    "code": "SR",
    "name": "Suriname",
    "file": "assets/Maps/Locator/Countries/sr.svg",
    "markerXPercent": 34.469,
    "markerYPercent": 47.698
  },
  "SS": {
    "code": "SS",
    "name": "South Sudan",
    "file": "assets/Maps/Locator/Countries/ss.svg",
    "markerXPercent": 58.442,
    "markerYPercent": 45.983
  },
  "ST": {
    "code": "ST",
    "name": "São Tomé and Príncipe",
    "file": "assets/Maps/Locator/Countries/st.svg",
    "markerXPercent": 51.95,
    "markerYPercent": 49.461
  },
  "SV": {
    "code": "SV",
    "name": "El Salvador",
    "file": "assets/Maps/Locator/Countries/sv.svg",
    "markerXPercent": 25.308,
    "markerYPercent": 42.397
  },
  "SX": {
    "code": "SX",
    "name": "Sint Maarten",
    "file": "assets/Maps/Locator/Countries/sx.svg",
    "markerXPercent": 32.481,
    "markerYPercent": 39.977
  },
  "SY": {
    "code": "SY",
    "name": "Syria",
    "file": "assets/Maps/Locator/Countries/sy.svg",
    "markerXPercent": 60.633,
    "markerYPercent": 30.552
  },
  "SZ": {
    "code": "SZ",
    "name": "Eswatini",
    "file": "assets/Maps/Locator/Countries/sz.svg",
    "markerXPercent": 58.741,
    "markerYPercent": 64.741
  },
  "TC": {
    "code": "TC",
    "name": "Turks and Caicos Islands",
    "file": "assets/Maps/Locator/Countries/tc.svg",
    "markerXPercent": 30.069,
    "markerYPercent": 37.88
  },
  "TD": {
    "code": "TD",
    "name": "Chad",
    "file": "assets/Maps/Locator/Countries/td.svg",
    "markerXPercent": 55.179,
    "markerYPercent": 41.587
  },
  "TF": {
    "code": "TF",
    "name": "French Southern and Antarctic Lands",
    "file": "assets/Maps/Locator/Countries/tf.svg",
    "markerXPercent": 69.201,
    "markerYPercent": 77.391
  },
  "TG": {
    "code": "TG",
    "name": "Togo",
    "file": "assets/Maps/Locator/Countries/tg.svg",
    "markerXPercent": 50.294,
    "markerYPercent": 45.107
  },
  "TH": {
    "code": "TH",
    "name": "Thailand",
    "file": "assets/Maps/Locator/Countries/th.svg",
    "markerXPercent": 78.076,
    "markerYPercent": 41.411
  },
  "TJ": {
    "code": "TJ",
    "name": "Tajikistan",
    "file": "assets/Maps/Locator/Countries/tj.svg",
    "markerXPercent": 70.163,
    "markerYPercent": 28.778
  },
  "TL": {
    "code": "TL",
    "name": "East Timor",
    "file": "assets/Maps/Locator/Countries/tl.svg",
    "markerXPercent": 84.96,
    "markerYPercent": 54.891
  },
  "TM": {
    "code": "TM",
    "name": "Turkmenistan",
    "file": "assets/Maps/Locator/Countries/tm.svg",
    "markerXPercent": 66.299,
    "markerYPercent": 27.858
  },
  "TN": {
    "code": "TN",
    "name": "Tunisia",
    "file": "assets/Maps/Locator/Countries/tn.svg",
    "markerXPercent": 52.502,
    "markerYPercent": 31.285
  },
  "TO": {
    "code": "TO",
    "name": "Tonga",
    "file": "assets/Maps/Locator/Countries/to.svg",
    "markerXPercent": 1.344,
    "markerYPercent": 61.783
  },
  "TR": {
    "code": "TR",
    "name": "Turkey",
    "file": "assets/Maps/Locator/Countries/tr.svg",
    "markerXPercent": 59.586,
    "markerYPercent": 28.141
  },
  "TT": {
    "code": "TT",
    "name": "Trinidad and Tobago",
    "file": "assets/Maps/Locator/Countries/tt.svg",
    "markerXPercent": 33.078,
    "markerYPercent": 43.889
  },
  "TV": {
    "code": "TV",
    "name": "Tuvalu",
    "file": "assets/Maps/Locator/Countries/tv.svg",
    "markerXPercent": 99.78,
    "markerYPercent": 54.73
  },
  "TW": {
    "code": "TW",
    "name": "Taiwan",
    "file": "assets/Maps/Locator/Countries/tw.svg",
    "markerXPercent": 83.575,
    "markerYPercent": 36.86
  },
  "TZ": {
    "code": "TZ",
    "name": "Tanzania",
    "file": "assets/Maps/Locator/Countries/tz.svg",
    "markerXPercent": 59.711,
    "markerYPercent": 53.362
  },
  "UA": {
    "code": "UA",
    "name": "Ukraine",
    "file": "assets/Maps/Locator/Countries/ua.svg",
    "markerXPercent": 58.928,
    "markerYPercent": 22.375
  },
  "UG": {
    "code": "UG",
    "name": "Uganda",
    "file": "assets/Maps/Locator/Countries/ug.svg",
    "markerXPercent": 59.152,
    "markerYPercent": 48.904
  },
  "UM": {
    "code": "UM",
    "name": "United States Minor Outlying Islands",
    "file": "assets/Maps/Locator/Countries/um.svg",
    "markerXPercent": 96.29,
    "markerYPercent": 39.286
  },
  "US": {
    "code": "US",
    "name": "United States of America",
    "file": "assets/Maps/Locator/Countries/us.svg",
    "markerXPercent": 22.921,
    "markerYPercent": 28.034
  },
  "UY": {
    "code": "UY",
    "name": "Uruguay",
    "file": "assets/Maps/Locator/Countries/uy.svg",
    "markerXPercent": 34.454,
    "markerYPercent": 68.312
  },
  "UZ": {
    "code": "UZ",
    "name": "Uzbekistan",
    "file": "assets/Maps/Locator/Countries/uz.svg",
    "markerXPercent": 67.779,
    "markerYPercent": 26.837
  },
  "VA": {
    "code": "VA",
    "name": "Vatican City",
    "file": "assets/Maps/Locator/Countries/va.svg",
    "markerXPercent": 53.459,
    "markerYPercent": 26.72
  },
  "VC": {
    "code": "VC",
    "name": "Saint Vincent and the Grenadines",
    "file": "assets/Maps/Locator/Countries/vc.svg",
    "markerXPercent": 32.962,
    "markerYPercent": 42.729
  },
  "VE": {
    "code": "VE",
    "name": "Venezuela",
    "file": "assets/Maps/Locator/Countries/ve.svg",
    "markerXPercent": 32.056,
    "markerYPercent": 46.01
  },
  "VG": {
    "code": "VG",
    "name": "British Virgin Islands",
    "file": "assets/Maps/Locator/Countries/vg.svg",
    "markerXPercent": 32.045,
    "markerYPercent": 39.763
  },
  "VI": {
    "code": "VI",
    "name": "United States Virgin Islands",
    "file": "assets/Maps/Locator/Countries/vi.svg",
    "markerXPercent": 32.006,
    "markerYPercent": 40.141
  },
  "VN": {
    "code": "VN",
    "name": "Vietnam",
    "file": "assets/Maps/Locator/Countries/vn.svg",
    "markerXPercent": 79.274,
    "markerYPercent": 37.936
  },
  "VU": {
    "code": "VU",
    "name": "Vanuatu",
    "file": "assets/Maps/Locator/Countries/vu.svg",
    "markerXPercent": 96.364,
    "markerYPercent": 58.54
  },
  "WF": {
    "code": "WF",
    "name": "Wallis and Futuna",
    "file": "assets/Maps/Locator/Countries/wf.svg",
    "markerXPercent": 0.517,
    "markerYPercent": 57.937
  },
  "WS": {
    "code": "WS",
    "name": "Samoa",
    "file": "assets/Maps/Locator/Countries/ws.svg",
    "markerXPercent": 2.1,
    "markerYPercent": 57.577
  },
  "XK": {
    "code": "XK",
    "name": "Kosovo",
    "file": "assets/Maps/Locator/Countries/xk.svg",
    "markerXPercent": 55.795,
    "markerYPercent": 26.337
  },
  "YE": {
    "code": "YE",
    "name": "Yemen",
    "file": "assets/Maps/Locator/Countries/ye.svg",
    "markerXPercent": 62.743,
    "markerYPercent": 41.484
  },
  "ZA": {
    "code": "ZA",
    "name": "South Africa",
    "file": "assets/Maps/Locator/Countries/za.svg",
    "markerXPercent": 56.574,
    "markerYPercent": 66.505
  },
  "ZM": {
    "code": "ZM",
    "name": "Zambia",
    "file": "assets/Maps/Locator/Countries/zm.svg",
    "markerXPercent": 57.332,
    "markerYPercent": 58.145
  },
  "ZW": {
    "code": "ZW",
    "name": "Zimbabwe",
    "file": "assets/Maps/Locator/Countries/zw.svg",
    "markerXPercent": 58.313,
    "markerYPercent": 60.506
  }
} as const satisfies Record<string, CountryLocatorAsset>;

export const resolveCountryLocatorAsset = (
  code: string,
): CountryLocatorAsset | null => {
  const normalized =
    String(code ?? "")
      .trim()
      .toUpperCase();

  return (
    (
      COUNTRY_LOCATOR_ASSETS as Record<
        string,
        CountryLocatorAsset
      >
    )[normalized] ??
    null
  );
};
